# Generated by Django 3.0.5 on 2020-05-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('date', models.DateField(verbose_name='考试日期')),
                ('siteName', models.CharField(max_length=100, verbose_name='考点名称')),
                ('adress', models.CharField(max_length=100, verbose_name='考点地址')),
                ('examineeNum', models.IntegerField(verbose_name='考生人数')),
                ('examType', models.CharField(max_length=20, verbose_name='考试类别')),
                ('examMethod', models.CharField(max_length=20, verbose_name='考试方式')),
                ('remarks', models.TextField(max_length=500, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='examinee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='考生姓名')),
                ('idNumber', models.CharField(max_length=18, verbose_name='身份证号')),
                ('examId', models.CharField(max_length=11, verbose_name='准考证号')),
            ],
        ),
        migrations.CreateModel(
            name='examPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('workUnit', models.CharField(max_length=100, verbose_name='工作单位')),
                ('post', models.CharField(max_length=30, verbose_name='工作职务')),
                ('phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('role', models.CharField(max_length=20, verbose_name='考务岗位')),
                ('ifTemporary', models.BooleanField(verbose_name='是否临聘人员')),
                ('grade', models.IntegerField(verbose_name='评分')),
                ('remarks', models.TextField(max_length=500, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='examSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考点名称')),
                ('address', models.CharField(max_length=100, verbose_name='考点地址')),
                ('roomNum', models.IntegerField(verbose_name='考场数')),
                ('roomMaxNum', models.IntegerField(verbose_name='最大考场数')),
                ('chiefName', models.CharField(max_length=20, verbose_name='主考')),
                ('chiefPhone', models.CharField(max_length=11, verbose_name='主考联系方式')),
                ('directorName', models.CharField(max_length=20, verbose_name='考务负责人')),
                ('directorPhone', models.CharField(max_length=11, verbose_name='考务联系方式')),
                ('ifStandardized', models.BooleanField(verbose_name='是否标准化考场')),
                ('remarks', models.TextField(max_length=500, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='examStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='材料名称')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('stuffType', models.CharField(max_length=20, verbose_name='类别')),
                ('remarks', models.TextField(max_length=500, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='interviewNotification',
            fields=[
                ('theExaminee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mvc.examinee')),
                ('beginTime', models.DateTimeField(verbose_name='开始打印时间')),
                ('endTime', models.DateTimeField(verbose_name='结束打印时间')),
                ('ifQuery', models.BooleanField(verbose_name='是否已查询')),
                ('ifPrint', models.BooleanField(verbose_name='是否已打印')),
                ('theExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.exam')),
            ],
        ),
        migrations.CreateModel(
            name='admissionTicket',
            fields=[
                ('theExaminee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mvc.examinee')),
                ('beginTime', models.DateTimeField(verbose_name='开始打印时间')),
                ('endTime', models.DateTimeField(verbose_name='结束打印时间')),
                ('ifQuery', models.BooleanField(verbose_name='是否已查询')),
                ('ifPrint', models.BooleanField(verbose_name='是否已打印')),
                ('theExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.exam')),
            ],
        ),
    ]
