# Generated by Django 3.0.5 on 2020-05-13 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_auto_20200511_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
                ('size', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='文件大小')),
                ('path', models.CharField(max_length=200, verbose_name='文件路径')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 5, 13, 14, 52, 21, 373092), verbose_name='上传时间')),
            ],
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='theExaminee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mvc.Examinee'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='theExaminee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mvc.Examinee'),
        ),
    ]
