# Generated by Django 3.0.5 on 2020-05-13 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0003_auto_20200513_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='examId',
            field=models.CharField(blank=True, max_length=20, verbose_name='关联考试ID'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='theExaminee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mvc.Examinee'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 17, 9, 10, 885797), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='theExaminee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mvc.Examinee'),
        ),
    ]
