# Generated by Django 3.0.5 on 2020-05-14 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0004_auto_20200513_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinee',
            old_name='idNumber',
            new_name='IDNumber',
        ),
        migrations.RemoveField(
            model_name='admissionticket',
            name='theExam',
        ),
        migrations.RemoveField(
            model_name='admissionticket',
            name='theExaminee',
        ),
        migrations.RemoveField(
            model_name='examinee',
            name='examId',
        ),
        migrations.RemoveField(
            model_name='interviewnotification',
            name='theExam',
        ),
        migrations.RemoveField(
            model_name='interviewnotification',
            name='theExaminee',
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='ATID',
            field=models.CharField(default=111111, max_length=11, verbose_name='准考证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='IDNumber',
            field=models.CharField(default=11111111, max_length=18, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='考点地址'),
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 10, 35, 49, 862492), verbose_name='考试日期'),
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='examID',
            field=models.CharField(default=11, max_length=20, verbose_name='关联考试'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='name',
            field=models.CharField(default=111, max_length=20, verbose_name='考生姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='siteName',
            field=models.CharField(blank=True, max_length=100, verbose_name='考点名称'),
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='state',
            field=models.BooleanField(default='0', verbose_name='当前状态'),
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='考试科目'),
        ),
        migrations.AddField(
            model_name='examinee',
            name='ATID',
            field=models.CharField(default=11111, max_length=11, verbose_name='准考证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='ATID',
            field=models.CharField(default=1111111, max_length=11, verbose_name='准考证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='IDNumber',
            field=models.CharField(default=1111111, max_length=18, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='考点地址'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 10, 35, 49, 863461), verbose_name='考试日期'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='examID',
            field=models.CharField(default=1, max_length=20, verbose_name='关联考试'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='name',
            field=models.CharField(default=11, max_length=20, verbose_name='考生姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='siteName',
            field=models.CharField(blank=True, max_length=100, verbose_name='考点名称'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='state',
            field=models.BooleanField(default='0', verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='ifPrint',
            field=models.BooleanField(default='0', verbose_name='是否已打印'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='ifQuery',
            field=models.BooleanField(default='0', verbose_name='是否已查询'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='考点地址'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examMethod',
            field=models.CharField(choices=[('面试', '面试'), ('笔试', '笔试'), ('机考', '机考')], default=('笔试', '笔试'), max_length=20, verbose_name='考试形式'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examType',
            field=models.CharField(choices=[('公务员考录', '公务员考录'), ('事业招聘', '事业招聘'), ('专业技术资格', '专业技术资格'), ('社会化考试', '社会化考试')], default=('社会化考试', '社会化考试'), max_length=20, verbose_name='考试类别'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examineeNum',
            field=models.IntegerField(blank=True, verbose_name='考生人数'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='siteName',
            field=models.CharField(blank=True, max_length=100, verbose_name='考点名称'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 10, 35, 49, 864458), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='ifPrint',
            field=models.BooleanField(default='0', verbose_name='是否已打印'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='ifQuery',
            field=models.BooleanField(default='0', verbose_name='是否已查询'),
        ),
    ]
