# Generated by Django 3.0.5 on 2020-05-14 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0006_auto_20200514_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionticket',
            name='applyPosition',
            field=models.CharField(blank=True, max_length=100, verbose_name='报考职位'),
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='applyUnit',
            field=models.CharField(blank=True, max_length=100, verbose_name='报考单位'),
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='applyPosition',
            field=models.CharField(blank=True, max_length=100, verbose_name='报考职位'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='applyUnit',
            field=models.CharField(blank=True, max_length=100, verbose_name='报考单位'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 11, 5, 51, 816582), verbose_name='上传时间'),
        ),
    ]
