# Generated by Django 3.0.5 on 2020-05-14 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0007_auto_20200514_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionticket',
            old_name='subject',
            new_name='subjectName',
        ),
        migrations.AddField(
            model_name='admissionticket',
            name='subjectTime',
            field=models.CharField(blank=True, max_length=100, verbose_name='科目时间'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='checkInTime',
            field=models.CharField(blank=True, max_length=20, verbose_name='报到时间'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='deadlineTime',
            field=models.CharField(blank=True, max_length=20, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='drawTime',
            field=models.CharField(blank=True, max_length=20, verbose_name='抽签时间'),
        ),
        migrations.AddField(
            model_name='interviewnotification',
            name='stratIVTime',
            field=models.CharField(blank=True, max_length=20, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 11, 40, 11, 802385), verbose_name='上传时间'),
        ),
    ]
