# Generated by Django 3.0.5 on 2020-05-14 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0011_auto_20200514_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionticket',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考点地址'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='applyPosition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考职位'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='applyUnit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考单位'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='beginTime',
            field=models.DateTimeField(null=True, verbose_name='开始打印时间'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='考试日期'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='endTime',
            field=models.DateTimeField(null=True, verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='siteName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考点名称'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='subjectName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='admissionticket',
            name='subjectTime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='科目时间'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 15, 46, 44, 642442), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考点地址'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='applyPosition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考职位'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='applyUnit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='报考单位'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='beginTime',
            field=models.DateTimeField(null=True, verbose_name='开始打印时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='checkInTime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='报到时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='考试日期'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='deadlineTime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='drawTime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='抽签时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='endTime',
            field=models.DateTimeField(null=True, verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='siteName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考点名称'),
        ),
        migrations.AlterField(
            model_name='interviewnotification',
            name='stratIVTime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='开始时间'),
        ),
    ]
