# Generated by Django 3.0.5 on 2020-05-15 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0014_auto_20200515_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsetinfo',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjectName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjectTime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='科目时间'),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='theExam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 10, 5, 28, 497355), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='insetinfo',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
    ]
