# Generated by Django 3.0.5 on 2020-05-15 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0016_auto_20200515_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insetinfo',
            old_name='stratIVTime',
            new_name='startIVTime',
        ),
        migrations.AlterField(
            model_name='atsetinfo',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='模板内容'),
        ),
        migrations.AlterField(
            model_name='atsetinfo',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='atsetinfo',
            name='state',
            field=models.BooleanField(default='0', verbose_name='是否启动'),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 14, 43, 13, 164375), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='insetinfo',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='模板内容'),
        ),
        migrations.AlterField(
            model_name='insetinfo',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='insetinfo',
            name='state',
            field=models.BooleanField(default='0', verbose_name='是否启动'),
        ),
    ]
