# Generated by Django 3.0.5 on 2020-05-15 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0019_auto_20200515_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsetinfo',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 16, 59, 12, 826934), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='insetinfo',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
    ]
