# Generated by Django 2.2.12 on 2020-05-16 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0022_auto_20200516_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subjectName',
            new_name='subject_1_Name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='subjectTime',
            new_name='subject_1_Time',
        ),
        migrations.AddField(
            model_name='atsetinfo',
            name='printType',
            field=models.CharField(choices=[('公务员考录', '公务员考录'), ('事业招聘', '事业招聘'), ('专业技术资格', '专业技术资格'), ('社会化考试', '社会化考试')], default=('社会化考试', '社会化考试'), max_length=20, verbose_name='模板类别'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_2_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考试科目'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_2_Time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='科目时间'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_3_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='考试科目'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_3_Time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='科目时间'),
        ),
        migrations.AddField(
            model_name='insetinfo',
            name='printType',
            field=models.CharField(choices=[('公务员考录', '公务员考录'), ('事业招聘', '事业招聘'), ('专业技术资格', '专业技术资格'), ('社会化考试', '社会化考试')], default=('社会化考试', '社会化考试'), max_length=20, verbose_name='模板类别'),
        ),
        migrations.AlterField(
            model_name='atsetinfo',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 21, 40, 47, 174618), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='insetinfo',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
    ]
