# Generated by Django 3.0.5 on 2020-05-18 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0024_auto_20200517_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='printTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beginTime', models.DateTimeField(null=True, verbose_name='开始打印时间')),
                ('endTime', models.DateTimeField(null=True, verbose_name='结束打印时间')),
                ('printType', models.CharField(choices=[('公务员考录', '公务员考录'), ('事业招聘', '事业招聘'), ('专业技术资格', '专业技术资格'), ('社会化考试', '社会化考试')], default=('社会化考试', '社会化考试'), max_length=20, verbose_name='模板类别')),
                ('content', tinymce.models.HTMLField(verbose_name='模板内容')),
                ('ifBase', models.BooleanField(default='0', verbose_name='是否基础模板')),
                ('state', models.BooleanField(default='0', verbose_name='是否启动')),
                ('loginURL', models.CharField(blank=True, max_length=200, null=True, verbose_name='登录网址')),
                ('exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试')),
            ],
        ),
        migrations.RemoveField(
            model_name='insetinfo',
            name='exam',
        ),
        migrations.AlterField(
            model_name='examinee',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 10, 36, 36, 483046), verbose_name='上传时间'),
        ),
        migrations.DeleteModel(
            name='ATSetInfo',
        ),
        migrations.DeleteModel(
            name='INSetInfo',
        ),
    ]
