# Generated by Django 3.0.5 on 2020-05-18 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0025_auto_20200518_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinee',
            name='theExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 10, 50, 21, 203853), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='beginTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始打印时间'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束打印时间'),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Exam', verbose_name='关联考试'),
        ),
    ]
